language: csharp
mono: none
dotnet: 2.0.0
script:
 - dotnet restore
 - dotnet build
 - dotnet test ./ImporterTests/ImporterTests.csproj
deploy:
- provider: script
  script: "./travis-deploy.sh" 
  on: master